### ISSUE TITLE
spinnaker对接AWS后无法正常启动的故障解决

### ISSUE THREAD

**Issue by zweizhang** [spinnaker-cn/clouddriver#21]
Hi 您好，

我在中国区安装spinnaker 遇到了provider aws enable后部署失败的问题，想请教下您该如何处理。

目前我们的spinnaker 部署在AWS EKS上，可以成功管理多个不同AWS账号下EKS集群，也即是 provider kubernets enable是没有问题的。但是当我想enable provider aws ，就出现了各种问题。clouddriver部署失败。
aws 的hal config配置如下：
```
    aws:
      enabled: true
      accounts:
      - name: aws-1
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        accountId: '11111111111'
        regions:
        - name: cn-north-1
        assumeRole: arn:aws-cn:iam::11111111111:role/spinnaker-releng
      - name: aws-2
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        accountId: '2222222222222'
        regions:
        - name: cn-north-1
        assumeRole: arn:aws-cn:iam::2222222222222:role/spinnaker-releng
      primaryAccount: aws-1
      bakeryDefaults:
        baseImages: []
      defaultKeyPairTemplate: '{{name}}-keypair'
      defaultRegions:
      - name: cn-north-1
      defaults:
        iamRole: BaseIAMRole
```
clouddrivcer pod的log如下：
```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cacheView' defined in class path resource [com/netflix/spinnaker/clouddriver/cache/CacheConfig.class]: Unsatisfied dependency expressed through method 'cacheView' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'catsModule' defined in class path resource [com/netflix/spinnaker/config/SqlCacheConfiguration.class]: Unsatisfied dependency expressed through method 'catsModule' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'netflixAmazonCredentials' defined in class path resource [com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsInitializer.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.List]: Factory method 'netflixAmazonCredentials' threw exception; nested exception is java.lang.UnsupportedOperationException: Client is immutable when created with the builder.
```
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'netflixAmazonCredentials' defined in class path resource [com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsInitializer.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.List]: Factory method 'netflixAmazonCredentials' threw exception; nested exception is java.lang.UnsupportedOperationException: Client is immutable when created with the builder.
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:635) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.
```

网上查找了很多资料，都说是aws cn的问题，但是没有找到最后的解决方法，希望可以从您这里获得帮助，谢谢~~

Best regards
Ray Zhang

**Comment by zweizhang** [comment]
版本1.23.7 遇到clouddriver的问题。
直接部署最新版本1.26.4 解决了这个问题。
目前可以同时管理AWS和k8s资源。
